# Rest Client

# @host = http://localhost:3000
@host = http://localhost:7080

### Get Users
GET {{host}}/users

### Create User
POST {{host}}/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password",
  "name": "Test User"
}

### Get User
GET {{host}}/users/1

### Update User
PUT {{host}}/users/1
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "password",
  "name": "Test User 2"
}

### Delete User
DELETE {{host}}/users/1
